import type { Product } from './types';

// This file is now just a mirror of the backend data for local development.
// The single source of truth is `server/utils/product-data.js`.
// This ensures the frontend and backend see the exact same data.

export const mockProducts: Product[] = [
  {
    id: "prod-111",
    name: "HECTOR 10%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/520342368Hectorsachy.jpeg"],
    rating: 4.5,
    reviews: 15,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Lambda Cyhalothrin 100gm/kg (10.00% w/w). Packing - 80GM , 240GM"
  },
  {
    id: "prod-69",
    name: "CEEDO 20%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/963441673Ceedo.png"],
    rating: 4.6,
    reviews: 22,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "It is a latest and unique insecticide chemistry which is from group neonictinoid. It has a contact,.... Packing - 150ML"
  },
  {
    id: "prod-128",
    name: "TRIDEMEFONE 25%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1340720766Triademafone.jpeg"],
    rating: 4.7,
    reviews: 18,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Triadimefon 250g/kg (25%Wp). Packing - 100GM"
  },
  {
    id: "prod-54",
    name: "PURE HUMUS 10%",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/10568pure-humus-soil-conditioner.png"],
    rating: 4.8,
    reviews: 35,
    isSoldOut: false,
    imageHint: "nutrient container",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "PURE HUMUS Soil Conditioner This a soil conditioner which increases production up to 10%. It.... Packing - 4Ltr , 8Ltr , 20Ltr , 30Ltr"
  },
  {
    id: "prod-123",
    name: "ORCUS 75%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/99258872Orcus.jpeg"],
    rating: 4.4,
    reviews: 12,
    isSoldOut: false,
    imageHint: "weedicide container",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Halosulfuron Methyl 75% w/w. Packing - 20GM"
  },
  {
    id: "prod-88",
    name: "RACER 360EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1763852958Delamethrin+Triazophos_product.jpeg"],
    rating: 4.5,
    reviews: 28,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Delamethrin+Triazophos 360EC. Packing - 200GM"
  },
  {
    id: "prod-16",
    name: "LAMBDA CYHALOTHRIN 2.5%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/18250lambda-cyhalothring-2.5-ec.jpeg"],
    rating: 4.7,
    reviews: 40,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "LAMBDA Cyhalothrin 2.5%EC Lambda is a pesticide belongs to advance research of Parathroid group.... Packing - 250ML , 500ML , 1000ML"
  },
  {
    id: "prod-122",
    name: "MISSION POSSIBLE 50%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/781639325MissionPossible.jpeg"],
    rating: 4.6,
    reviews: 19,
    isSoldOut: false,
    imageHint: "weedicide container",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Mesotrione: 100 g/Kg (10% w/w), Atrazine: 400 g/Kg (40% w/w). Packing - 400GM , 1KG"
  },
  {
    id: "prod-49",
    name: "SINGLE 80% WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/28409sulphur-80-wg.png"],
    rating: 4.8,
    reviews: 33,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "SINGLE is broad range fungicide whose ingredient is Sulphur which is made by specific procedure. It.... Packing - 1KG"
  },
  {
    id: "prod-115",
    name: "SUDAO 11.6%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1547377629Sudao100ml.png"],
    rating: 4.5,
    reviews: 14,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Emamectin Benzoate 25 gm/ltr.(2.45% w/w) + Chlorantraniliprole 90 gm/ltr. (8.50% w/w). Packing - 100ML"
  },
  {
    id: "prod-103",
    name: "ACEPHATE 75% SP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/232997538Acephate.jpg"],
    rating: 4.6,
    reviews: 25,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Acephate 750 gm/kg (75% w/w). Packing - 250GM"
  },
  {
    id: "prod-132",
    name: "TRAINER",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1817541670Trainer-new.jpg"],
    rating: 4.9,
    reviews: 50,
    isSoldOut: false,
    imageHint: "nutrient bottle",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "Complex /Blend of Amino Acid and Plant Growth Regulator. Packing - 400ML , 800ML"
  },
  {
    id: "prod-17",
    name: "LUFENURON 5%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/5819LUFENURON-5-EC-683x1024.png"],
    rating: 4.5,
    reviews: 21,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Lufenuron eliminates bollworm by influencing their growth. Lefeunuron is a growth inhibitor.... Packing - 400ML , 1000ML"
  },
  {
    id: "prod-76",
    name: "LIGHT 25%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/618054907Light.jpeg"],
    rating: 4.7,
    reviews: 30,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Exact and long-time control against sucking pests. Gives the excellent crop stand by making it pest.... Packing - 48GM"
  },
  {
    id: "prod-127",
    name: "PIVOT 18.7%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/14793143Pivot.jpeg"],
    rating: 4.6,
    reviews: 16,
    isSoldOut: false,
    imageHint: "fungicide box",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Pyraclostrobin 67g/Kg (6.7% w/w) + Dimethomorph 120 g/kg (12% w/w). Packing - 200GM"
  },
  {
    id: "prod-106",
    name: "CHLORFENAPYR 360SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1135537743Chlorfenapyre.jpeg"],
    rating: 4.5,
    reviews: 23,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Chlorfenapyr 360 G/L (31.0% w/w). Packing - 200ML"
  },
  {
    id: "prod-14",
    name: "IMIDACLOPRID 25%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/31561imidacloprid-70-ws.jpeg"],
    rating: 4.4,
    reviews: 29,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "N/A. Packing - 100GM"
  },
  {
    id: "prod-119",
    name: "BURJ 75%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1384177484Burj.jpeg"],
    rating: 4.6,
    reviews: 11,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Sulfosufuron 75% w/w. Packing - 13.5GM"
  },
  {
    id: "prod-133",
    name: "CARTAP 4%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/902813422Cartapppp.png"],
    rating: 4.7,
    reviews: 38,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Granules",
    subcategory: "granules",
    tags: ["granules"],
    description: "Cartap Hydrochloride 40 g/kg (4% w/w). Packing - 9KG"
  },
  {
    id: "prod-94",
    name: "SEED CARE 300FS",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1286045188Seed_Care_product.png"],
    rating: 4.8,
    reviews: 45,
    isSoldOut: false,
    imageHint: "seed treatment bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Seed Care 300FS. Packing - 50ML , 100ML"
  },
  {
    id: "prod-135",
    name: "CORNER 27%Zinc",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1371848144Corner3.jpg"],
    rating: 4.9,
    reviews: 60,
    isSoldOut: false,
    imageHint: "fertilizer bag",
    category: "Fertilizers",
    subcategory: "fertilizers",
    tags: ["fertilizers"],
    description: "Zinc...............(270g/kg) 27% w/w. Packing - 9KG"
  },
  {
    id: "prod-80",
    name: "SHORT 13%OD",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1679911833Short.png"],
    rating: 4.5,
    reviews: 17,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Very effective mixture weedicide against grass like weeds in wheat even in very low temperature..... Packing - 300ML"
  },
  {
    id: "prod-31",
    name: "MISSION EXTRA 55%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/8755mission-extra-55-sc.jpeg"],
    rating: 4.6,
    reviews: 24,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Mission Extra is a wide range selective weedicide which eradicates Grassy, Broadleaf and Sedges in.... Packing - 500ML , 1000ML"
  },
  {
    id: "prod-116",
    name: "VALOR 12%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1697495855valor.jpeg"],
    rating: 4.7,
    reviews: 13,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Abamectin 20 G/L (1.80 % w/w) + Thiamethoxam 100 G/L (9% w/w). Packing - 400ML"
  },
  {
    id: "prod-2",
    name: "ACETAMEPRID 20%SP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/6380acetamiprid-20-sp.jpg"],
    rating: 4.5,
    reviews: 31,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "ACETAMIPRID 20%SP Acetamiprid is a new selective discovery according to advance demands for control.... Packing - 250GM"
  },
  {
    id: "prod-113",
    name: "KING POCKER 25%EW",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/115527771King_Pocker-bg.png"],
    rating: 4.8,
    reviews: 20,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Carbosulfan (230 G/L) 20% w/w Emamectin Benzoate (20 G/L) 1.74% w/w. Packing - 200ML"
  },
  {
    id: "prod-129",
    name: "TRIP 250SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1987333082Trip-bg.png"],
    rating: 4.6,
    reviews: 10,
    isSoldOut: false,
    imageHint: "fungicide bottle",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Iprodione 20% w/v (18.5% w/w) + Tebuconazole 5% w/v (4.6% w/w). Packing - 125ML"
  },
  {
    id: "prod-79",
    name: "SHIDING 21%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/560759570Shiding.jpeg"],
    rating: 4.6,
    reviews: 26,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Shiding is the best mixture insecticide having a combination of two different grouped insecticide..... Packing - 250ML , 800ML"
  },
  {
    id: "prod-104",
    name: "LEERA 80%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/2014729525Leera.png"],
    rating: 4.7,
    reviews: 17,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Leera is the best insecticide against sucking pest and mites as well. It has contact and stomach.... Packing - 150GM"
  },
  {
    id: "prod-37",
    name: "PARAZONE 20%SL",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/4463paraquat-20-sl.jpeg"],
    rating: 4.5,
    reviews: 29,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "PARAZONE 20%SL Very effective non-selective PARAZONE has ability to eliminate all grass like and.... Packing - 1000ML"
  },
  {
    id: "prod-30",
    name: "KICK 48%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/30114kick-48-sc.png"],
    rating: 4.6,
    reviews: 21,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "KICK 48%SC Kick is a mixture of three weedicides which successively controls the broadleaf weeds.... Packing - 350ML"
  },
  {
    id: "prod-126",
    name: "WAKER 50%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1658160518Walker300ml.png"],
    rating: 4.7,
    reviews: 18,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Fluroxypyr-Meptyl: 100 G/Ltr (8.85% w/w), Mcpa-Isooctyl: 370 g/ltr (32.74%), Bromoxynil: 50 g/ltr.... Packing - 300ML"
  },
  {
    id: "prod-72",
    name: "SUPER PLUS 6%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/132520509Super.jpg"],
    rating: 4.8,
    reviews: 25,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Super Plus is a systemic wheat weedicide which controls the all types of grass-like and broadleaf.... Packing - 110GM"
  },
  {
    id: "prod-114",
    name: "SOVISECT 50%SP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1498527914Sovisect.jpeg"],
    rating: 4.9,
    reviews: 32,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Thiocyclam Hydrogen Oxalate 50% w/w. Packing - 100GM"
  },
  {
    id: "prod-70",
    name: "CONDO 30%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/138648226Condo.png"],
    rating: 4.5,
    reviews: 20,
    isSoldOut: false,
    imageHint: "fungicide bottle",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "New, latest and broad-spectrum fungicide. It protects the old foliage and the new as well due to.... Packing - 300ML"
  },
  {
    id: "prod-33",
    name: "METRIBUZIN 70%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/19305METRIBUZIN-70WP-683x1024.jpeg"],
    rating: 4.6,
    reviews: 28,
    isSoldOut: false,
    imageHint: "weedicide bag",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Metribuzin is wide range weedicide which eliminates weeds in crops of Potato and Wheat. Its.... Packing - 250GM"
  },
  {
    id: "prod-81",
    name: "SKATER 15%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1603655310Skater.png"],
    rating: 4.7,
    reviews: 19,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Broadspectrum post-emergence weedicide for grass-like weeds in all broadleaf crops.. Packing - 400ML"
  },
  {
    id: "prod-105",
    name: "BIFENTHRIN 10% EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1412141642Bifenthrin.png"],
    rating: 4.8,
    reviews: 35,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Bifenthrin 100 gm/Ltr. (10.6% w/w). Packing - 500ML , 1000ML"
  },
  {
    id: "prod-84",
    name: "MULTICLEAN 25%OD",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/459180245Multi-Clean.png"],
    rating: 4.9,
    reviews: 41,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Multiclean is a systemic wheat weedicide which controls the all types of grass-like and broadleaf.... Packing - 350ML"
  },
  {
    id: "prod-109",
    name: "EMAMECTIN 1.9%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/757741861Emamectin.png"],
    rating: 4.5,
    reviews: 24,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Emamectin Benzoate 19 G/L (2.04% w/w). Packing - 200ML , 400ML , 1000ML"
  },
  {
    id: "prod-57",
    name: "SAVER PEDAWAR 10%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/14279SAVER-PAIDAWAR-10DANAYDAR-768x1024.png"],
    rating: 4.6,
    reviews: 33,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients", "granules"],
    description: "Crop Suppliment. A compound to fulfill the deficiency of Zinc and other major elements like.... Packing - 4KG"
  },
  {
    id: "prod-67",
    name: "SAJAJAN",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1132570839Sajjan.jpeg"],
    rating: 4.7,
    reviews: 29,
    isSoldOut: false,
    imageHint: "nutrient container",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "It is the unique and latest crop nutrient therapy. It has chelated nutrients including zinc and is.... Packing - 200GM"
  },
  {
    id: "prod-117",
    name: "WOOLMER 3%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1332648517Woolmer400ml.png"],
    rating: 4.8,
    reviews: 22,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Emamectin Benzoate 10 gm/ltr. (0.94% w/w) + Lufenuron 20 gm/ltr. (1.88% w/w). Packing - 400ML , 1000ML"
  },
  {
    id: "prod-118",
    name: "ATRAZINE 38%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1220103988Atrazin.jpeg"],
    rating: 4.9,
    reviews: 15,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Atrazine 380 gm/ltr  (34.3% w/w). Packing - 500ML , 1000ML"
  },
  {
    id: "prod-131",
    name: "SAVERON Boron 5%",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/2132996493Saveron.jpg"],
    rating: 4.5,
    reviews: 38,
    isSoldOut: false,
    imageHint: "nutrient bottle",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "Boron…..... 5% w/v (50 G/L). Packing - 500ML"
  },
  {
    id: "prod-64",
    name: "ENERGY 5%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/23938monomehypo-5g.png"],
    rating: 4.6,
    reviews: 27,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Granules",
    subcategory: "granules",
    tags: ["granules"],
    description: "Monomehypo is an advanced and most effective pesticide for rich production of Rice. Being systemic,.... Packing - 7KG"
  },
  {
    id: "prod-108",
    name: "DINO 200SG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/197718019Dino.jpeg"],
    rating: 4.7,
    reviews: 31,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Dinotefuran 20% w/w. Packing - 120GM"
  },
  {
    id: "prod-60",
    name: "KALLIUM S",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/15250kallium-s.png"],
    rating: 4.8,
    reviews: 42,
    isSoldOut: false,
    imageHint: "fertilizer bag",
    category: "Fertilizers",
    subcategory: "fertilizers",
    tags: ["fertilizers"],
    description: "Water Soluble Feritlizer. Kalluim-S is a unique fertilizer which has 50% of Potash and also.... Packing - 10KG , 25KG"
  },
  {
    id: "prod-125",
    name: "SPECTAR 20%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1178014332Spector.jpeg"],
    rating: 4.9,
    reviews: 19,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Metamifop 80 G/L(8% w/w) + Cyhalofop Butyl 120 G/L(12% w/w). Packing - 300ML"
  },
  {
    id: "prod-50",
    name: "THIOPHENATE 70% WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/20030THIOPHANATE-METHYL-70-683x1024.jpeg"],
    rating: 4.5,
    reviews: 34,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Thiophanate Methyle is a wide range Systemic fungicide. Its real active is capable of both as.... Packing - 400GM"
  },
  {
    id: "prod-46",
    name: "PROFILE 47%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/30711PROFILE-47FUNGICIDE-683x1024.jpeg"],
    rating: 4.6,
    reviews: 23,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "PROFILE 47%WP Profile is a combination of two elements Kasugamycin and Copper Oxychloride which is.... Packing - 200GM , 500GM"
  },
  {
    id: "prod-26",
    name: "BROMOXYNIL 40%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/31046bromoxynil-40-ec.png"],
    rating: 4.7,
    reviews: 28,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "N/A. Packing - 400ML , 800ML"
  },
  {
    id: "prod-110",
    name: "FIPRONIL 5%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/11693581Fipronil480ml.png"],
    rating: 4.8,
    reviews: 36,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Fipronil 50 G/L (4.65% w/w). Packing - 480ML"
  },
  {
    id: "prod-62",
    name: "WINSTO 30%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/27855WNSTA-30WP-e1518088107905-731x1024.png"],
    rating: 4.9,
    reviews: 25,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Winsta eliminates pointed leaf, braoadleaf and other grass like weeds of rice crop effectively. It.... Packing - 100GM"
  },
  {
    id: "prod-120",
    name: "DEMO 20%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1663843375Demo.png"],
    rating: 4.5,
    reviews: 20,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Metsulfuron Methyl 200 gm/Kg (20% w/w). Packing - 20GM"
  },
  {
    id: "prod-63",
    name: "FIPRONIL 0.4%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/9497fipronil-0.4-g.png"],
    rating: 4.6,
    reviews: 30,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Granules",
    subcategory: "granules",
    tags: ["granules"],
    description: "Fipronil is a systemic pesticide which kills the pests by eating and contacting. Other than rice,.... Packing - 6KG"
  },
  {
    id: "prod-95",
    name: "ACUBAR 30%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1192552725ACUBAR-removebg-preview.jpeg"],
    rating: 4.7,
    reviews: 26,
    isSoldOut: false,
    imageHint: "weedicide bag",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "ACUBAR (Bensulfuron 6.7% + Acetachlor 23.3 %) Pre Emergence weedicide for the complete control of .... Packing - 150GM"
  },
  {
    id: "prod-53",
    name: "JEET",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/2027jeet-poassium-humate-solid.png"],
    rating: 4.8,
    reviews: 39,
    isSoldOut: false,
    imageHint: "nutrient bag",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "JEET Potassium Humate Solid. Jeet is a soil conditioner. It increases production upto 10 %. Jeet is.... Packing - 8KG , 20KG"
  },
  {
    id: "prod-27",
    name: "CLODINOFOP 15%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/9991clodinafop-propargly-15-wp.jpeg"],
    rating: 4.5,
    reviews: 27,
    isSoldOut: false,
    imageHint: "weedicide bag",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Clodinafop is for Wild Oat, Bird’s Seed Grass and other Grass like weeds which harms wheat.... Packing - 160GM"
  },
  {
    id: "prod-59",
    name: "ADVANCER",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/11549advancer.png"],
    rating: 4.7,
    reviews: 35,
    isSoldOut: false,
    imageHint: "fertilizer bag",
    category: "Fertilizers",
    subcategory: "fertilizers",
    tags: ["fertilizers"],
    description: "It contains 14% Nitrogen and 44% Phosphorous. It can be used as Nutrigation by drip. It is 100%.... Packing - 8KG"
  },
  {
    id: "prod-134",
    name: "MARCH 0.2%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/59481214March.jpeg"],
    rating: 4.8,
    reviews: 29,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Granules",
    subcategory: "granules",
    tags: ["granules"],
    description: "Chlorantraniloprole: 0.2% w/w. Packing - 8KG"
  },
  {
    id: "prod-74",
    name: "GOAL 36%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1549943618Goal.png"],
    rating: 4.9,
    reviews: 40,
    isSoldOut: false,
    imageHint: "fungicide box",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "It is a mixture of two very strong fungicides and has both the contact and systemic way of action..... Packing - 250GM , 1KG"
  },
  {
    id: "prod-121",
    name: "FAST PLUS 88.8%WSG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/2030827368Fast-Plus.jpeg"],
    rating: 4.6,
    reviews: 22,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Glyphosate 888gm/kg (88.8% w/w). Packing - 50GM"
  },
  {
    id: "prod-112",
    name: "INSTANT SUPER 50%SG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/2066664533Instentsuper.jpeg"],
    rating: 4.7,
    reviews: 33,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Nitenpyram 500 gm/kg (50% w/w). Packing - 50GM"
  },
  {
    id: "prod-66",
    name: "SNIPER",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/1450393423Sniper.png"],
    rating: 4.8,
    reviews: 45,
    isSoldOut: false,
    imageHint: "nutrient bag",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "Nitrogen in the Sniper increases the growth of the plants.Sniper is suitable for gardening.The.... Packing - 1KG"
  },
  {
    id: "prod-19",
    name: "SPEED 50%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["https://saverenterprises.com/uploadfiles/26417speed-10-wdg.jpeg"],
    rating: 4.9,
    reviews: 50,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Speed is an advance IGR belongs to Benzoylurea group which inhibits the Chitin building process by.... Packing - 100ML"
  }
];

    