import type { Product } from './types';

export const mockProducts: Product[] = [
  // Insecticides
  {
    id: 'insect-1',
    name: 'Contact Insecticide',
    brand: 'FMC',
    price: 1250,
    images: ['https://placehold.co/400x400'],
    rating: 4.5,
    reviews: 112,
    isSoldOut: false,
    imageHint: 'insecticide bottle',
    category: 'insecticides',
    subcategory: 'contact',
    tags: ['pest-control', 'fast-acting']
  },
  {
    id: 'insect-2',
    name: 'Systemic Insecticide',
    brand: 'Bayer',
    price: 1800,
    originalPrice: 2000,
    images: ['https://placehold.co/400x400'],
    rating: 4.8,
    reviews: 210,
    isSoldOut: false,
    imageHint: 'systemic insecticide',
    category: 'insecticides',
    subcategory: 'systemic',
    tags: ['long-lasting', 'plant-protection']
  },
  {
    id: 'insect-3',
    name: 'Neem Oil (Biological)',
    brand: 'Organic Farmers Co.',
    price: 950,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 302,
    isSoldOut: false,
    imageHint: 'neem oil bottle',
    category: 'insecticides',
    subcategory: 'biological',
    tags: ['organic', 'eco-friendly']
  },

  // Herbicides
  {
    id: 'herbi-1',
    name: 'Pre-emergence Herbicide',
    brand: 'Engro',
    price: 1800,
    images: ['https://placehold.co/400x400'],
    rating: 4.6,
    reviews: 88,
    isSoldOut: false,
    imageHint: 'herbicide granules',
    category: 'herbicides',
    subcategory: 'pre-emergence',
    tags: ['weed-prevention', 'seasonal']
  },
  {
    id: 'herbi-2',
    name: 'Post-emergence Spray',
    brand: 'Syngenta',
    price: 2100,
    images: ['https://placehold.co/400x400'],
    rating: 4.7,
    reviews: 150,
    isSoldOut: true,
    imageHint: 'herbicide spray bottle',
    category: 'herbicides',
    subcategory: 'post-emergence',
    tags: ['weed-killer', 'fast-acting']
  },
  {
    id: 'herbi-3',
    name: 'Non-selective Herbicide',
    brand: 'Syngenta',
    price: 2400,
    images: ['https://placehold.co/400x400'],
    rating: 4.4,
    reviews: 75,
    isSoldOut: false,
    imageHint: 'industrial herbicide',
    category: 'herbicides',
    subcategory: 'non-selective',
    tags: ['total-kill', 'industrial-use']
  },

  // Fungicides
  {
    id: 'fungi-1',
    name: 'Preventive Fungicide',
    brand: 'Bayer',
    price: 1500,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 180,
    isSoldOut: false,
    imageHint: 'fungicide powder',
    category: 'fungicides',
    subcategory: 'preventive',
    tags: ['disease-control', 'protection']
  },
  {
    id: 'fungi-2',
    name: 'Curative Fungicide',
    brand: 'FMC',
    price: 1950,
    images: ['https://placehold.co/400x400'],
    rating: 4.7,
    reviews: 95,
    isSoldOut: false,
    imageHint: 'liquid fungicide',
    category: 'fungicides',
    subcategory: 'curative',
    tags: ['treatment', 'fast-acting']
  },
   {
    id: 'fungi-3',
    name: 'Systemic Fungicide (Advanced)',
    brand: 'Syngenta',
    price: 2800,
    images: ['https://placehold.co/400x400'],
    rating: 5,
    reviews: 212,
    isSoldOut: false,
    imageHint: 'systemic fungicide bottle',
    category: 'fungicides',
    subcategory: 'systemic',
    tags: ['long-lasting', 'broad-spectrum']
  },

  // Fertilizers
  {
    id: 'fert-1',
    name: 'NPK Fertilizer (20-20-20)',
    brand: 'Engro',
    price: 3500,
    images: ['https://placehold.co/400x400'],
    rating: 5,
    reviews: 254,
    isSoldOut: true,
    imageHint: 'fertilizer bag',
    category: 'fertilizers',
    subcategory: 'npk',
    tags: ['balanced-nutrition', 'all-purpose']
  },
  {
    id: 'fert-2',
    name: 'Urea Fertilizer',
    brand: 'FFC',
    price: 2800,
    images: ['https://placehold.co/400x400'],
    rating: 4.8,
    reviews: 450,
    isSoldOut: false,
    imageHint: 'urea bag',
    category: 'fertilizers',
    subcategory: 'urea',
    tags: ['high-nitrogen', 'growth-booster']
  },
  {
    id: 'fert-3',
    name: 'DAP Fertilizer',
    brand: 'Engro',
    price: 4200,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 380,
    isSoldOut: false,
    imageHint: 'dap fertilizer bag',
    category: 'fertilizers',
    subcategory: 'dap',
    tags: ['phosphorus-rich', 'root-development']
  },
  {
    id: 'fert-4',
    name: 'Organic Compost',
    brand: 'Green Earth Organics',
    price: 1200,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 150,
    isSoldOut: false,
    imageHint: 'compost bag',
    category: 'fertilizers',
    subcategory: 'organic',
    tags: ['soil-health', 'eco-friendly']
  },
  
  // Seeds
  {
    id: 'seed-1',
    name: 'Hybrid Wheat Seeds',
    brand: 'Maher Seeds',
    price: 4200,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 310,
    isSoldOut: false,
    imageHint: 'wheat seeds bag',
    category: 'seeds',
    subcategory: 'wheat',
    tags: ['high-yield', 'disease-resistant']
  },
  {
    id: 'seed-2',
    name: 'Basmati Rice Seeds',
    brand: 'Maher Seeds',
    price: 5500,
    originalPrice: 5800,
    images: ['https://placehold.co/400x400'],
    rating: 4.8,
    reviews: 250,
    isSoldOut: false,
    imageHint: 'rice seeds bag',
    category: 'seeds',
    subcategory: 'rice',
    tags: ['aromatic', 'premium-quality']
  },
  {
    id: 'seed-3',
    name: 'BT Cotton Seeds',
    brand: 'Maher Seeds',
    price: 6500,
    images: ['https://placehold.co/400x400'],
    rating: 4.9,
    reviews: 400,
    isSoldOut: true,
    imageHint: 'cotton seeds packet',
    category: 'seeds',
    subcategory: 'cotton',
    tags: ['pest-resistant', 'high-yield']
  },
  {
    id: 'seed-4',
    name: 'Hybrid Tomato Seeds',
    brand: 'ProSeeds',
    price: 800,
    images: ['https://placehold.co/400x400'],
    rating: 4.7,
    reviews: 120,
    isSoldOut: false,
    imageHint: 'tomato seeds packet',
    category: 'seeds',
    subcategory: 'vegetables',
    tags: ['hybrid', 'gardening']
  }
];
