services:
  - type: web
    name: my-backend
    env: node
    plan: free
    region: oregon
    rootDir: server
    build_command: npm install
    start_command: node index.js
    env_vars:
      - key: MONGO_URI
        fromSecret: true
