
// =================================================================================
// THIS IS YOUR MASTER PRODUCT LIST
// =================================================================================
// This is the ONLY file you need to edit to add, remove, or change your products.
// After you edit this file, run the following command in your terminal
// to update your live database:
//
// npm run seed --prefix server
//
// =================================================================================

const mockProducts = [
  {
    id: "prod-111",
    name: "HECTOR 10%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/520342368Hectorsachy.jpeg"],
    rating: 4.5,
    reviews: 15,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Lambda Cyhalothrin 100gm/kg (10.00% w/w)"
  },
  {
    id: "prod-69",
    name: "CEEDO 20%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/963441673Ceedo.png"],
    rating: 4.6,
    reviews: 22,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "It is a latest and unique insecticide chemistry which is from group neonictinoid. It has a contact,..."
  },
  {
    id: "prod-128",
    name: "TRIDEMEFONE 25%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1340720766Triademafone.jpeg"],
    rating: 4.7,
    reviews: 18,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Triadimefon 250g/kg (25%Wp)"
  },
  {
    id: "prod-54",
    name: "PURE HUMUS 10%",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/10568pure-humus-soil-conditioner.png"],
    rating: 4.8,
    reviews: 35,
    isSoldOut: false,
    imageHint: "nutrient container",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "PURE HUMUS Soil Conditioner This a soil conditioner which increases production up to 10%. It..."
  },
  {
    id: "prod-123",
    name: "ORCUS 75%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/99258872Orcus.jpeg"],
    rating: 4.4,
    reviews: 12,
    isSoldOut: false,
    imageHint: "weedicide container",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Halosulfuron Methyl 75% w/w"
  },
  {
    id: "prod-88",
    name: "RACER 360EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1763852958Delamethrin+Triazophos_product.jpeg"],
    rating: 4.5,
    reviews: 28,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Delamethrin+Triazophos 360EC"
  },
  {
    id: "prod-16",
    name: "LAMBDA CYHALOTHRIN 2.5%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/18250lambda-cyhalothring-2.5-ec.jpeg"],
    rating: 4.7,
    reviews: 40,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "LAMBDA Cyhalothrin 2.5%EC Lambda is a pesticide belongs to advance research of Parathroid group..."
  },
  {
    id: "prod-122",
    name: "MISSION POSSIBLE 50%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/781639325MissionPossible.jpeg"],
    rating: 4.6,
    reviews: 19,
    isSoldOut: false,
    imageHint: "weedicide container",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Mesotrione: 100 g/Kg (10% w/w), Atrazine: 400 g/Kg (40% w/w)"
  },
  {
    id: "prod-49",
    name: "SINGLE 80% WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/28409sulphur-80-wg.png"],
    rating: 4.8,
    reviews: 33,
    isSoldOut: false,
    imageHint: "fungicide bag",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "SINGLE is broad range fungicide whose ingredient is Sulphur which is made by specific procedure. It..."
  },
  {
    id: "prod-115",
    name: "SUDAO 11.6%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1547377629Sudao100ml.png"],
    rating: 4.5,
    reviews: 14,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Emamectin Benzoate 25 gm/ltr.(2.45% w/w) + Chlorantraniliprole 90 gm/ltr. (8.50% w/w)"
  },
  {
    id: "prod-103",
    name: "ACEPHATE 75% SP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/232997538Acephate.jpg"],
    rating: 4.6,
    reviews: 25,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Acephate 750 gm/kg (75% w/w)"
  },
  {
    id: "prod-132",
    name: "TRAINER",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1817541670Trainer-new.jpg"],
    rating: 4.9,
    reviews: 50,
    isSoldOut: false,
    imageHint: "nutrient bottle",
    category: "Micro Nutrients",
    subcategory: "micro-nutrients",
    tags: ["micro-nutrients"],
    description: "Complex /Blend of Amino Acid and Plant Growth Regulator"
  },
  {
    id: "prod-17",
    name: "LUFENURON 5%EC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/5819LUFENURON-5-EC-683x1024.png"],
    rating: 4.5,
    reviews: 21,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Lufenuron eliminates bollworm by influencing their growth. Lefeunuron is a growth inhibitor..."
  },
  {
    id: "prod-76",
    name: "LIGHT 25%WDG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/618054907Light.jpeg"],
    rating: 4.7,
    reviews: 30,
    isSoldOut: false,
    imageHint: "insecticide box",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Exact and long-time control against sucking pests. Gives the excellent crop stand by making it pest..."
  },
  {
    id: "prod-127",
    name: "PIVOT 18.7%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/14793143Pivot.jpeg"],
    rating: 4.6,
    reviews: 16,
    isSoldOut: false,
    imageHint: "fungicide box",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Pyraclostrobin 67g/Kg (6.7% w/w) + Dimethomorph 120 g/kg (12% w/w)"
  },
  {
    id: "prod-106",
    name: "CHLORFENAPYR 360SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1135537743Chlorfenapyre.jpeg"],
    rating: 4.5,
    reviews: 23,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Chlorfenapyr 360 G/L (31.0% w/w)"
  },
  {
    id: "prod-14",
    name: "IMIDACLOPRID 25%WP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/31561imidacloprid-70-ws.jpeg"],
    rating: 4.4,
    reviews: 29,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "N/A"
  },
  {
    id: "prod-119",
    name: "BURJ 75%WG",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1384177484Burj.jpeg"],
    rating: 4.6,
    reviews: 11,
    isSoldOut: false,
    imageHint: "weedicide box",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Sulfosufuron 75% w/w"
  },
  {
    id: "prod-133",
    name: "CARTAP 4%G",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/902813422Cartapppp.png"],
    rating: 4.7,
    reviews: 38,
    isSoldOut: false,
    imageHint: "granules bag",
    category: "Granules",
    subcategory: "granules",
    tags: ["granules"],
    description: "Cartap Hydrochloride 40 g/kg (4% w/w)"
  },
  {
    id: "prod-94",
    name: "SEED CARE 300FS",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1286045188Seed_Care_product.png"],
    rating: 4.8,
    reviews: 45,
    isSoldOut: false,
    imageHint: "seed treatment bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Seed Care 300FS"
  },
  {
    id: "prod-135",
    name: "CORNER 27%Zinc",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1371848144Corner3.jpg"],
    rating: 4.9,
    reviews: 60,
    isSoldOut: false,
    imageHint: "fertilizer bag",
    category: "Fertilizers",
    subcategory: "fertilizers",
    tags: ["fertilizers"],
    description: "Zinc...............(270g/kg) 27% w/w"
  },
  {
    id: "prod-80",
    name: "SHORT 13%OD",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1679911833Short.png"],
    rating: 4.5,
    reviews: 17,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Very effective mixture weedicide against grass like weeds in wheat even in very low temperature...."
  },
  {
    id: "prod-31",
    name: "MISSION EXTRA 55%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/8755mission-extra-55-sc.jpeg"],
    rating: 4.6,
    reviews: 24,
    isSoldOut: false,
    imageHint: "weedicide bottle",
    category: "Weedicides",
    subcategory: "weedicides",
    tags: ["weedicides"],
    description: "Mission Extra is a wide range selective weedicide which eradicates Grassy, Broadleaf and Sedges in..."
  },
  {
    id: "prod-116",
    name: "VALOR 12%SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1697495855valor.jpeg"],
    rating: 4.7,
    reviews: 13,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Abamectin 20 G/L (1.80 % w/w) + Thiamethoxam 100 G/L (9% w/w)"
  },
  {
    id: "prod-2",
    name: "ACETAMEPRID 20%SP",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/6380acetamiprid-20-sp.jpg"],
    rating: 4.5,
    reviews: 31,
    isSoldOut: false,
    imageHint: "insecticide powder",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "ACETAMIPRID 20%SP Acetamiprid is a new selective discovery according to advance demands for control..."
  },
  {
    id: "prod-113",
    name: "KING POCKER 25%EW",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/115527771King_Pocker-bg.png"],
    rating: 4.8,
    reviews: 20,
    isSoldOut: false,
    imageHint: "insecticide bottle",
    category: "Insecticides",
    subcategory: "insecticides",
    tags: ["insecticides"],
    description: "Carbosulfan (230 G/L) 20% w/w Emamectin Benzoate (20 G/L) 1.74% w/w"
  },
  {
    id: "prod-129",
    name: "TRIP 250SC",
    brand: "Saver Enterprises",
    price: 0,
    images: ["http://saverenterprises.com/uploadfiles/1987333082Trip-bg.png"],
    rating: 4.6,
    reviews: 10,
    isSoldOut: false,
    imageHint: "fungicide bottle",
    category: "Fungicides",
    subcategory: "fungicides",
    tags: ["fungicides"],
    description: "Iprodione 20% w/v (18.5% w/w) + Tebuconazole 5% w/v (4.6% w/w)"
  }
];

module.exports = { mockProducts };
